# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  cut_rc_release:
    default: false
    type: boolean
  trigger_pr_release:
    default: false
    type: boolean
  trigger_merge_release:
    default: false
    type: boolean
  version_name:
    type: string
    default: ""
  pr_number:
    type: integer
    default: 0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  open_pull_request_release:
    macos:
      xcode: &xcode-img 13.4.1
    parameters:
      version:
        type: string
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Open PR from stabilization branch into releases
          command: |
            bundle exec fastlane open_pr_release  \
            version:"<< parameters.version >>"

  merge_and_publish_release:
    macos:
      xcode: &xcode-img 13.4.1
    parameters:
      pr_number:
        type: integer
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Merge Release PR & Publish Release
          command: |
            bundle exec fastlane merge_publish_release  \
            pr_number: "#{parameters.pr_number.to_i}"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  create_release_trigger:
    when: << pipeline.parameters.trigger_pr_release >>
    jobs:
      - open_pull_request_release:
          version: << pipeline.parameters.version_name >>

  merge_release_trigger:
    when: << pipeline.parameters.trigger_merge_release >>
    jobs:
      - merge_and_publish_release:
          pr_number: << pipeline.parameters.pr_number >>
